### ISSUE TITLE
Multiple dir folders

### ISSUE THREAD

**Issue by borsosl** [js-seth-h/grunt-fast-watch#1]
This plugin works great for a single dir folder.
When it's an array, it has a JS error trying to use the replace function on the array.

Is it possible to add this feature?
I'm not familiar with coffescript...

**Comment by js-seth-h** [comment]
I guess, it is a solution creating multiple task configuration. like following..

<pre>
  grunt.initConfig 
    fastWatch:
      cwd:     
        dir : '.' 
        ignoreSubDir : ignoreDir 
        trigger:
          ....
     dir2:      
        dir : 'some other dir' 
        ignoreSubDir : ignoreDir 
        trigger: 
</pre>
